### ISSUE TITLE
Issue with the filter

### ISSUE THREAD

**Issue by pergolafabio** [straybiker/HA-load-balancer#10]
There is solar now
so my grid comsumtion is 0

![Image](https://github.com/user-attachments/assets/6e62f0d0-58e0-4a49-b23b-bf2bc25bba27)

But my netto verbruik stays behind? thats not good ?? 

![Image](https://github.com/user-attachments/assets/56af32f7-db4b-48e9-90b9-2f29f0c20b38)

```
sensor:
  - platform: filter
    name: "Netto verbruik huis LP"
    unique_id: netto_verbruik_huis_lp
    entity_id: sensor.grid_consumption
    filters:
     - filter: outlier
       window_size: 4
       radius: 500.0
     - filter: lowpass
       time_constant: 12
       precision: 2
```
