### ISSUE TITLE
Req; Maybe create also a package for a simplified setup

### ISSUE THREAD

**Issue by pergolafabio** [straybiker/HA-load-balancer#11]
Below is the automation that doesnt check a real car live status, no battery check, no extra limit power ... an simplified versions suitable for more users

Maybe add 2 versions of your code?

Here is mine now (untested yet)
```
# 1) Use netto as a sensor in the filter below, this is the netto power (Grid usage - solar - alfen power)
# 2) Define a load balancing limit in the input_helper
# 3) Change entity names in the script/automation for the alfen charger if yours are different
# 4) Change time pattern in the automation, its now defined as 30 sec, dont go lower as 10!

sensor:
  - platform: filter
    name: "Netto Verbruik Huis LB"
    unique_id: netto_verbruik_huis_lp
    entity_id: sensor.grid_consumption_netto
    filters:
     - filter: outlier
       window_size: 4
       radius: 500.0
     - filter: lowpass
       time_constant: 12
       precision: 2

input_number:
  ev_load_balancing_power_limit:
    name: EV Load Balancing Power Limit
    icon: mdi:flash
    mode: slider
    unit_of_measurement: W
    min: 1500
    max: 12000
    step: 250

input_select:
  ev_charge_mode:
    name: EV Charge Mode
    icon: mdi:ev-station
    options:
      - Off
      - Minimal 1.4kW
      - Minimal 4kW
      - Eco
      - Fast

template:
  - sensor:
      - name: Alfen Connection State
        unique_id: alfen_connection_state
        state: >
          {% set m3 = states('sensor.alfen_mode3_state_socket_1') %}
          {% if m3 in ['STATE_A', 'STATE_E'] %} Disconnected
          {% elif m3 in ['STATE_B1', 'STATE_B2', 'STATE_C1', 'STATE_D1', 'STATE_C2', 'STATE_D2'] %} Connected
          {% elif m3 in ['STATE_F'] %} Error
          {% else %} Disconnected
          {% endif %}

script:
  set_pv_charging_parameter:
    alias: Set EV charging parameter
    sequence:
      - variables:
          finalcurrent: |-
            {% if current < 6 %}
              0
            {% else %}
              {{ current }}
            {% endif %}
      - alias: Set phases
        if:
          - alias: If phase change
            condition: template
            value_template: >-
              {{ phase != states('select.alfen_installation_max_allowed_phases')
              }}
        then:
          - action: select.select_option
            metadata: {}
            data:
              option: "{{ phase }}"
            target:
              entity_id: select.alfen_installation_max_allowed_phases
          - delay:
              hours: 0
              minutes: 0
              seconds: 30
            enabled: true
      - alias: Set current
        if:
          - condition: template
            value_template: >-
              {{ finalcurrent | int !=
              states('number.alfen_power_connector_max_current_socket_1') | int }}
            enabled: true
        then:
          - action: number.set_value
            metadata: {}
            data:
              value: "{{ finalcurrent }}"
            target:
              entity_id: number.alfen_power_connector_max_current_socket_1
          - delay:
              hours: 0
              minutes: 0
              seconds: 30
            enabled: true
    description: ""
    icon: mdi:ev-station
    fields:
      phase:
        selector:
          select:
            options:
              - 1 Phase
              - 3 Phases
            multiple: false
        name: phase
        required: false
        description: EV charging phase [1 Phase, 3 Phases]
        default: 1 Phase
      current:
        selector:
          number:
            min: 0
            max: 16
            step: 1
        name: current
        required: true
        default: 6
        description: EV charging current


automation:
  - alias: Reset chargepoint
    initial_state: 'on'
    description: >-
      Reset the charger phase and current when the car is disconnected to prevent
      the charger being stuck at low settings when HA becomes unavailable
    triggers:
      - trigger: state
        entity_id:
          - sensor.alfen_connection_state
        for:
          hours: 0
          minutes: 1
          seconds: 0
        to: "Disconnected"
    conditions: []
    actions:
      - action: script.set_pv_charging_parameter
        metadata: {}
        data:
          current: 6
          phase: 3 Phases
        target:
          entity_id: script.set_pv_charging_parameter
    mode: single
    
  - alias: Load Balance EV Charging
    initial_state: 'on'
    description: ""
    triggers:
      - trigger: time_pattern
        seconds: /30
      - trigger: state
        entity_id:
          - input_select.ev_charge_mode
          - input_number.ev_load_balancing_power_limit
    conditions:
      - condition: state
        entity_id: sensor.alfen_connection_state
        state: "Connected"
    actions:
      - variables:
          home_power: "{{ states('sensor.netto_verbruik_huis_lp') | int }}"
          max_combined_power: "{{ states('input_number.ev_load_balancing_power_limit') | int }}"
          max_current: "{{ 16 | int }}"
          min_current: "{{ 6 | int }}"
          available_power: >
            {% set power_left = max_combined_power - home_power %}  {{ power_left if
            power_left > 0 else 0 }}
          phase_selection: "{{ 3 if available_power >= (230 * min_current * 3) else 1 }}"
          current_limit: >
            {% set current = (available_power / (230 * phase_selection)) |
            int %}  {% if current | int < min_current %}
              0
            {% elif current > max_current %}
              {{ max_current }}
            {% else %}
              {{ current }}
            {% endif %}
      - choose:
          # Off
          - conditions:
              - condition: state
                entity_id: input_select.ev_charge_mode
                state: "Off"
            sequence:
              - action: script.set_pv_charging_parameter
                metadata: {}
                data:
                  current: 0
                  phase: 3 Phases
                target:
                  entity_id: script.set_pv_charging_parameter
          - conditions:
          # Minimal 1.4kW
              - condition: state
                entity_id: input_select.ev_charge_mode
                state: "Minimal 1.4kW"
            sequence:
              - action: script.set_pv_charging_parameter
                metadata: {}
                data:
                  current: 6
                  phase: 1 Phase
                target:
                  entity_id: script.set_pv_charging_parameter
          - conditions:
          # Minimal 4kW
              - condition: state
                entity_id: input_select.ev_charge_mode
                state: "Minimal 4kW"
            sequence:
              - action: script.set_pv_charging_parameter
                metadata: {}
                data:
                  current: 6
                  phase: 3 Phases
                target:
                  entity_id: script.set_pv_charging_parameter
          - conditions:
          # Fast
              - condition: state
                entity_id: input_select.ev_charge_mode
                state: "Fast"
            sequence:
              - action: script.set_pv_charging_parameter
                metadata: {}
                data:
                  current: 16
                  phase: 3 Phases
                target:
                  entity_id: script.set_pv_charging_parameter
          - conditions:
          # Eco
              - condition: state
                entity_id: input_select.ev_charge_mode
                state: "Eco"
            sequence:
              - action: script.set_pv_charging_parameter
                metadata: {}
                data:
                  current: "{{ current_limit | int }}"
                  phase: "{{ '1 Phase' if phase_selection == 1 else '3 Phases' }}"
                target:
                  entity_id: script.set_pv_charging_parameter
    mode: single


```

**Comment by straybiker** [comment]
Thanks! Will have a look at if if I spot any problems and add it

**Comment by pergolafabio** [comment]
now its running at eco 6000, time pattern is 30 sec , but i see connection errors to the alfen, some drops, it doesnt impact the charging, but what can cause this? is it sending data? allthough the automation should not, since its charging at the same Ampere?

```
2025-02-24 11:40:20.253 ERROR (MainThread) [custom_components.alfen_wallbox.coordinator] Timeout fetching alfen_wallbox data
2025-02-24 11:44:00.210 WARNING (MainThread) [homeassistant.components.automation.load_balance_ev_charging] Load Balance EV Charging: Already running
2025-02-24 11:45:28.049 WARNING (MainThread) [homeassistant.components.automation.load_balance_ev_charging] Load Balance EV Charging: Already running
2025-02-24 11:45:30.208 WARNING (MainThread) [homeassistant.components.automation.load_balance_ev_charging] Load Balance EV Charging: Already running
2025-02-24 11:46:18.629 WARNING (MainThread) [homeassistant.components.automation.load_balance_ev_charging] Load Balance EV Charging: Already running
2025-02-24 11:47:08.541 WARNING (MainThread) [homeassistant.components.automation.load_balance_ev_charging] Load Balance EV Charging: Already running
2025-02-24 11:53:50.443 ERROR (MainThread) [custom_components.alfen_wallbox.coordinator] Timeout fetching alfen_wallbox data
2025-02-24 11:58:20.252 ERROR (MainThread) [custom_components.alfen_wallbox.coordinator] Timeout fetching alfen_wallbox data
```

![Image](https://github.com/user-attachments/assets/4b7a0f35-b91c-4043-8845-eaca090301e0)

**Comment by pergolafabio** [comment]
ok, this is better :-)

now the script doesnt run when not needed....

          - condition: template
            value_template: >-
              {{ finalcurrent | int !=
              states('number.alfen_power_connector_max_current_socket_1') | int }}

**Comment by pergolafabio** [comment]
and also , are you sure the desction below is needed? i think it doenst do anything? those values are incorrect?


![Image](https://github.com/user-attachments/assets/677fc5db-25d1-4d95-8d93-4b472e0c604f)

![Image](https://github.com/user-attachments/assets/03911924-3964-4910-9123-ee0b5dd7c450)

**Comment by pergolafabio** [comment]
what i dont understand : 

```
      - alias: Set phases
        if:
          - alias: If phase change
            condition: template
            value_template: >-
              {{ phase != states('select.alfen_installation_max_allowed_phases')
              }}
        then:
          - action: select.select_option
            metadata: {}
            data:
              option: "{{ phase }}"
            target:
              entity_id: select.alfen_installation_max_allowed_phases
```

where is your "{{ phase }}" coming from?  i dont see it in the variables?
is it coming from  below fields is the phase stored in the fields? if yes
why is it "required: false" WHats the purpose of that?
Also in below screenshot  i never see that phase/current changing there? its always 1 phase / 6

```
    description: ""
    icon: mdi:ev-station
    fields:
      phase:
        selector:
          select:
            options:
              - 1 Phase
              - 3 Phases
            multiple: false
        name: phase
        required: false
        description: EV charging phase [1 Phase, 3 Phases]
        default: 1 Phase
```

![Image](https://github.com/user-attachments/assets/37b276ab-b5cd-46f4-b4af-5296e599a80b)

**Comment by straybiker** [comment]
Those are indeed the input parameters coming from the automation calling the script. It is optional and if omitted it defaults to 1 phase, 6A

**Comment by pergolafabio** [comment]
ok , i edited first post...
Changed the current condition, that doesnt make the script run every time when current isnt changed, i believe its wrong in your code?
```

              {{ finalcurrent | int !=
              states('number.alfen_power_connector_max_current_socket_1') | int }}
```

Also changed the state: triggeres with quotes, i dont think it works without?
These ones ...
```
        to: "Disconnected"
                state: "Minimal 4kW"
```
and some more

and changed the template sensor , so it can only be connected OR disconnected , and NOT unavaible

**Comment by straybiker** [comment]
> i tested above , but my reset script didnt trigger, i changed the states
> 
> ` to: Disconnected`
> 
> to:
> 
> ` to: "Disconnected"`
> 
> also changed in in the te other automation, like:
> 
> ```
>         entity_id: sensor.alfen_connection_state
>         state: "Connected"
> ```
> 
> ```
>           # Minimal 1.4kW
>               - condition: state
>                 entity_id: input_select.ev_charge_mode
>                 state: "Minimal 1.4kW"
> ```
> 
> i believe it must be between quotes?
> 


Odd, it works here without quotes

![Image](https://github.com/user-attachments/assets/ef175ac7-1140-4ef2-acc5-6963fa337c9e)

**Comment by straybiker** [comment]
> ```
> template:
>   - sensor:
>       - name: Alfen Connection State
>         unique_id: alfen_connection_state
>         state: >
>           {% set m3 = states('sensor.alfen_mode3_state_socket_1') %}
>           {% if m3 in ['STATE_A', 'STATE_E'] %} Disconnected
>           {% elif m3 in ['STATE_B1', 'STATE_B2', 'STATE_C1', 'STATE_D1', 'STATE_C2', 'STATE_D2'] %} Connected
>           {% elif m3 in ['STATE_F'] %} Error
>           {% else %} Unavaible
>           {% endif %}
> ```
> 
> into this:
> 
> ```
> template:
>   - sensor:
>       - name: Alfen Connection State
>         unique_id: alfen_connection_state
>         state: >
>           {% set m3 = states('sensor.alfen_mode3_state_socket_1') %}
>           {% if m3 in ['STATE_A', 'STATE_E'] %} Disconnected
>           {% elif m3 in ['STATE_B1', 'STATE_B2', 'STATE_C1', 'STATE_D1', 'STATE_C2', 'STATE_D2'] %} Connected
>           {% elif m3 in ['STATE_F'] %} Error
>           {% else %} Disconnected
>           {% endif %}
> ```
> 
> cause in my case its always unavaible, and maybe when the polling is wrong from the alfen, it never gives the state ['STATE_A', 'STATE_E'] , so the sensor will then skip the "disconnected" state


Ok, but this will result in a charger reset if somehow the communication to the charger fails, such as a timeout. Don't know if you want this. Maybe better to ignore this state or use Error state

**Comment by straybiker** [comment]
> now its running at eco 6000, time pattern is 30 sec , but i see connection errors to the alfen, some drops, it doesnt impact the charging, but what can cause this? is it sending data? allthough the automation should not, since its charging at the same Ampere?
> 
> ```
> 2025-02-24 11:40:20.253 ERROR (MainThread) [custom_components.alfen_wallbox.coordinator] Timeout fetching alfen_wallbox data
> 2025-02-24 11:44:00.210 WARNING (MainThread) [homeassistant.components.automation.load_balance_ev_charging] Load Balance EV Charging: Already running
> 2025-02-24 11:45:28.049 WARNING (MainThread) [homeassistant.components.automation.load_balance_ev_charging] Load Balance EV Charging: Already running
> 2025-02-24 11:45:30.208 WARNING (MainThread) [homeassistant.components.automation.load_balance_ev_charging] Load Balance EV Charging: Already running
> 2025-02-24 11:46:18.629 WARNING (MainThread) [homeassistant.components.automation.load_balance_ev_charging] Load Balance EV Charging: Already running
> 2025-02-24 11:47:08.541 WARNING (MainThread) [homeassistant.components.automation.load_balance_ev_charging] Load Balance EV Charging: Already running
> 2025-02-24 11:53:50.443 ERROR (MainThread) [custom_components.alfen_wallbox.coordinator] Timeout fetching alfen_wallbox data
> 2025-02-24 11:58:20.252 ERROR (MainThread) [custom_components.alfen_wallbox.coordinator] Timeout fetching alfen_wallbox data
> ```
> 
> disregard the high peak below , bt notice the drops (connection timeouts)
> 
> ![Image](https://github.com/user-attachments/assets/4b7a0f35-b91c-4043-8845-eaca090301e0)

Don't know, I have these timeout as well. Maybe communication with the CPO is ongoing at this moment

**Comment by pergolafabio** [comment]
What about below, want that wrong in your original code? I saw in your code the script always running , even when it was not needed to change the current...
Not sure what happens if you always set the number entity to the same value over and over again, is it actually sending the curent to the Alfen? Maybe that's causing timeouts too


```
              {{ finalcurrent | int !=
              states('number.alfen_power_connector_max_current_socket_1') | int }}
```

**Comment by pergolafabio** [comment]
> 
> Ok, but this will result in a charger reset if somehow the communication to the charger fails, such as a timeout. Don't know if you want this. Maybe better to ignore this state or use Error state
........


Well, the problem is, I only see this state for a few seconds 

['STATE_A', 'STATE_E']

It immediately changes to unknown aftererwards, so I think if the polling is on a bad timing, it never sees the state ['STATE_A', 'STATE_E'] , and therefore it skips the state "disconnected"...
You always see : ['STATE_A', 'STATE_E'] on your mode3 sensor if the car is not connected??

**Comment by straybiker** [comment]
State seems OK here. Maybe a fw thing

![Image](https://github.com/user-attachments/assets/2b5bb32e-45d8-44bb-be00-98eca0219bf1)

**Comment by pergolafabio** [comment]
Ok , time to upgrade my Alfen :-)

**Comment by straybiker** [comment]
Ok, let me know the results so I can update the prerequisites in the documentation

**Comment by pergolafabio** [comment]
Ok , will upgrade tomorrow!

**Comment by pergolafabio** [comment]
hmm, updated to 7.1.3 , but still see unknown!! :-)
Firmware: 7.1.3-4342

What version are you running? im running 2.9.4 

![Image](https://github.com/user-attachments/assets/26bedfd8-42ab-4b36-97e6-6b8726b0e393)

**Comment by straybiker** [comment]
2.9.4 of the integration and 7.1.0 of the firmware

**Comment by straybiker** [comment]
You can find a description in the Alfen modbus documentation

**Comment by pergolafabio** [comment]
ok, thats a difficult one, its meaning its connected to alfen , but not charging ... that means when we are doing LB, and sending 0A to pause charging, it will also go in state B2  ...

![Image](https://github.com/user-attachments/assets/70fefedb-bc9e-43b3-af5e-192cfd052e7f)

**Comment by pergolafabio** [comment]
i was charging, disconnected the cable, the state was "disconnected" , but then to error, cause of the unkown state ...
My reset chargepoint script didnt trigger, is it maybe because the minutes: 1 is too long?
should i shorten it?

```
automation:
  - alias: Reset chargepoint
    initial_state: 'on'
    description: >-
      Reset the charger phase and current when the car is disconnected to prevent
      the charger being stuck at low settings when HA becomes unavailable
    triggers:
      - trigger: state
        entity_id:
          - sensor.alfen_connection_state
        for:
          hours: 0
          minutes: 1
          seconds: 0
```

![Image](https://github.com/user-attachments/assets/b71b0810-ced3-49a6-9f57-9e8372f5de81)
