### ISSUE TITLE
Packages

### ISSUE THREAD

**Issue by pergolafabio** [straybiker/HA-load-balancer#3]
Hey @straybiker , createsd  a package for you , i think i have everything, didnt test yet, maybe i created a typo somewhere for the helpers, but i believe its very usefull and will sure help others, especially with the helpers ...

anyway, add this line below in your configuration.yaml in the home assistant section

for some reason the "off" option in the input select doesnt display "Off" for me ... i think using the word "Off" is a bad choice 
for an option ...

ALso added an initital state for the automation to "on" 

```
homeassistant:
  packages: !include_dir_named packages
```

Afterwards create a folder "packages" and drop the below content into 1 yaml file of your choice

```

sensor:
  - platform: filter
    name: "Netto verbruik huis LP"
    unique_id: netto_verbruik_huis_lp
    entity_id: sensor.netto_verbruik_huis
    filters:
     - filter: outlier
       window_size: 4
       radius: 500.0
     - filter: lowpass
       time_constant: 12
       precision: 2

input_number:
  alfen_eve_power_efficiency:
    name: Alfen Eve Power Efficiency
    icon: mdi:percent
    mode: slider
    min: 0
    max: 100
    step: 1
  ev_battery_capacity:
    name: EV Battery Capacity
    icon: mdi:car-battery
    mode: box
    unit_of_measurement: Wh
    min: 0
    max: 100000
    step: 1
  ev_load_balancer_extended_power_limit:
    name: EV Load Balancer Extended Power Limit
    icon: mdi:flash
    mode: slider
    unit_of_measurement: W
    min: 1500
    max: 12000
    step: 100
  ev_load_balancing_power_limit:
    name: EV Load Balancing Power Limit
    icon: mdi:flash
    mode: slider
    unit_of_measurement: W
    min: 1500
    max: 12000
    step: 100
  ev_soc_threshold:
    name: EV Soc Threshold
    icon: mdi:percent
    mode: slider
    min: 0
    max: 100
    step: 1

input_select:
  ev_charge_mode:
    name: EV Charge Mode
    icon: mdi:ev-station
    options:
      - Off
      - Minimal 1.4kW
      - Minimal 4kW
      - Eco
      - Fast

input_datetime:
  ev_charge_time_target:
    name: EV Charge Time Target
    icon: mdi:battery-clock-outline
    has_date: false
    has_time: true

script:
  set_pv_charging_parameter:
    alias: Set EV charging parameter
    sequence:
      - variables:
          finalcurrent: |-
            {% if current < 6 %}
              0
            {% else %}
              {{ current }}
            {% endif %}
      - alias: Set phases
        if:
          - alias: If phase change
            condition: template
            value_template: >-
              {{ phase != states('select.alfen_eve_installation_max_allowed_phases')
              }}
        then:
          - action: select.select_option
            metadata: {}
            data:
              option: "{{ phase }}"
            target:
              entity_id: select.alfen_eve_installation_max_allowed_phases
          - delay:
              hours: 0
              minutes: 0
              seconds: 10
            enabled: true
      - alias: Set current
        if:
          - condition: template
            value_template: >-
              {{ finalcurrent | int !=
              states('number.alfen_eve_power_connector_max_current_socket_1') }}
            enabled: true
        then:
          - action: number.set_value
            metadata: {}
            data:
              value: "{{ finalcurrent }}"
            target:
              entity_id: number.alfen_eve_power_connector_max_current_socket_1
          - delay:
              hours: 0
              minutes: 0
              seconds: 10
            enabled: true
    description: ""
    icon: mdi:ev-station
    fields:
      phase:
        selector:
          select:
            options:
              - 1 Phase
              - 3 Phases
            multiple: false
        name: phase
        required: false
        description: EV charging phase [1 Phase, 3 Phases]
        default: 1 Phase
      current:
        selector:
          number:
            min: 0
            max: 16
            step: 1
        name: current
        required: true
        default: 6
        description: EV charging current


automation:
  - alias: Load Balance EV Charging
    initial_state: 'on'
    description: ""
    triggers:
      - trigger: time_pattern
        seconds: /10
      - trigger: state
        entity_id:
          - input_select.ev_charge_mode
          - input_number.ev_load_balancing_power_limit
    conditions:
      - alias: Car is connected
        condition: template
        value_template: "{{ states('sensor.alfen_eve_status_code_socket_1') != 'Available' }}"
        enabled: true
    actions:
      - variables:
          home_power: "{{ states('sensor.netto_verbruik_huis_lp') | int }}"
          max_combined_power: "{{ states('input_number.ev_load_balancing_power_limit') | int }}"
          extended_power_limit: "{{ states('input_number.ev_load_balancer_extended_power_limit') | int }}"
          max_current: "{{ 16 | int }}"
          min_current: "{{ 6 | int }}"
          battery_percentage: "{{ states('sensor.ix3_m_sport_remaining_battery_percent') | int }}"
          current_time: "{{ now().strftime('%H:%M:%S') }}"
          time_until_target_time: >
            {% set now = now() %}    {% set target_time =
            states('input_datetime.ev_charge_time_target') %}   {% set target_hour =
            target_time[0:2] | int %}    {% set target_minute = target_time[3:5] |
            int %}  {% set target_datetime = now.replace(hour=target_hour,
            minute=target_minute, second=0, microsecond=0) %}   {% if
            target_datetime < now %}  {% set target_datetime = target_datetime +
            timedelta(days=1) %}   {% endif %}  {% set time_diff = (target_datetime
            - now).total_seconds() / 3600 %}   {{ time_diff | round(2) | float }}
          battery_capacity_wh: "{{ states('input_number.ev_battery_capacity') | int }}"
          soc_threshold: "{{ states('input_number.ev_soc_threshold') | int }}"
          charger_efficiency: "{{ states('input_number.alfen_eve_power_efficiency') | float / 100 }}"
          available_power: >
            {% set power_left = max_combined_power - home_power %}  {{ power_left if
            power_left > 0 else 0 }}
          adjusted_available_power: "{{ available_power / charger_efficiency }}"
          phase_selection: "{{ 3 if adjusted_available_power >= (230 * min_current * 3) else 1 }}"
          current_limit: >
            {% set current = (adjusted_available_power / (230 * phase_selection)) |
            int %}  {% if current | int < min_current %}
              0
            {% elif current > max_current %}
              {{ max_current }}
            {% else %}
              {{ current }}
            {% endif %}
          combined_power: "{{ home_power + (current_limit * 230 * phase_selection) }}"
          estimated_battery_percentage: >
            {% set charging_power = (current_limit * 230 * phase_selection) | float
            %}        {% set charging_time = time_until_target_time / 3600 %} {% set
            added_energy = (charging_power * charging_time | float) %} {{
            (((battery_capacity_wh * battery_percentage / 100) + added_energy) /
            battery_capacity_wh) * 100 }}
          power_limit: |
            {% if estimated_battery_percentage | int < soc_threshold %}
              {{ extended_power_limit }}
            {% else %}
              {{ max_combined_power }}
            {% endif %}
          adjusted_available_power_final: |
            {% set power_left = power_limit - home_power %} 
            {{ power_left / charger_efficiency if power_left > 0 else 0 }}
          adjusted_phase_selection: >-
            {{ 3 if adjusted_available_power_final >= (230 * min_current * 3) else 1
            }}
          adjusted_current_limit: >
            {% set current = (adjusted_available_power_final / (230 *
            adjusted_phase_selection)) | int %}

            {% if current | int < min_current %}
              0
            {% elif current > max_current %}
              {{ max_current }}
            {% else %}
              {{ current }}
            {% endif %}
      - choose:
          - conditions:
              - condition: state
                entity_id: input_select.ev_charge_mode
                state: "Off"
            sequence:
              - variables:
                  adjusted_phase_selection: 1
                  adjusted_current_limit: 0
                enabled: false
              - action: script.set_pv_charging_parameter
                metadata: {}
                data:
                  current: 0
                  phase: 3 Phases
                target:
                  entity_id: script.set_pv_charging_parameter
          - conditions:
              - condition: state
                entity_id: input_select.ev_charge_mode
                state: Minimal 1.4kW
            sequence:
              - variables:
                  adjusted_phase_selection: 1
                  adjusted_current_limit: 6
                enabled: false
              - action: script.set_pv_charging_parameter
                metadata: {}
                data:
                  current: 6
                  phase: 1 Phase
                target:
                  entity_id: script.set_pv_charging_parameter
          - conditions:
              - condition: state
                entity_id: input_select.ev_charge_mode
                state: Minimal 4kW
            sequence:
              - variables:
                  adjusted_phase_selection: 3
                  adjusted_current_limit: 6
                enabled: false
              - action: script.set_pv_charging_parameter
                metadata: {}
                data:
                  current: 6
                  phase: 3 Phases
                target:
                  entity_id: script.set_pv_charging_parameter
          - conditions:
              - condition: state
                entity_id: input_select.ev_charge_mode
                state: Fast
            sequence:
              - variables:
                  adjusted_phase_selection: 3
                  adjusted_current_limit: 16
                enabled: false
              - action: script.set_pv_charging_parameter
                metadata: {}
                data:
                  current: 16
                  phase: 3 Phases
                target:
                  entity_id: script.set_pv_charging_parameter
          - conditions:
              - condition: state
                entity_id: input_select.ev_charge_mode
                state: Eco
            sequence:
              - action: script.set_pv_charging_parameter
                metadata: {}
                data:
                  current: "{{ adjusted_current_limit | int }}"
                  phase: "{{ '1 Phase' if adjusted_phase_selection == 1 else '3 Phases' }}"
                target:
                  entity_id: script.set_pv_charging_parameter
    mode: single

```

**Comment by pergolafabio** [comment]
i believ this is a great start for making a good componnt, i know lots of people looking for this, especially for belgium, it you dont mind, can i share this on tweakers? :-)

**Comment by pergolafabio** [comment]
Btw, that graph you are showing on your readme page, is that a card, or are you just creating it on the history page and selecting entities?

**Comment by pergolafabio** [comment]
also, an idea to make a simplified version , without the battery/car/soc and the adjustable current/phases
for users that dont care or have multiple cars... or the automation should check first 'what car is charging and get the values from it' ... but i think its an overkill :-)

anyway, that automation to make sure thee Alfen is resetted to some value in case HA is down when its 0, is usefull too to drop in the package

**Comment by pergolafabio** [comment]
i also see this one in ths script:

`            value_template: "{{ finalcurrent | int != states('input_number.chargecurrent') | int }}"`

but that input number is missing in the documenation/screenshots right?

**Comment by pergolafabio** [comment]
also the stuff below in the script is not needed , right? i dont see you changing it, or i'm misunderstanding the purpose anwyay

```
    description: ""
    icon: mdi:ev-station
    fields:
      phase:
        selector:
          select:
            options:
              - 1 Phase
              - 3 Phases
            multiple: false
        name: phase
        required: false
        description: EV charging phase [1 Phase, 3 Phases]
        default: 1 Phase
      current:
        selector:
          number:
            min: 0
            max: 16
            step: 1
        name: current
        required: true
        default: 6
        description: EV charging current
```
